[package]
name = "herod_gba_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
herod_gba_core = { path = "../core/"}
minifb = "0.27"
simple_logger = "=5.0.0"
log = "0.4.22"
